name: guide-tem-simulation
channels:
  - conda-forge
dependencies:
  - 'python<3.12'
  - 'numpy<2'
  - scipy
  - h5py
  - matplotlib
  - colorspacious
  - abtem
  - ipywidgets
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
