name: guide-tem-simulation
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - h5py
  - matplotlib
  - abtem
  - ipywidgets
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
