name: guide-tem-simulation
channels:
  - conda-forge
dependencies:
  - scipy
  - h5py
  - matplotlib
  - ipywidgets
  - jupyterlab>=4.0.0
  - jupyterlab-myst>=2.0.0
  - pip
  - pip:
      - git+https://github.com/abtem/abtem